### ISSUE TITLE
Compiling with GSC Editor / Compiler gives me an error

### ISSUE THREAD

**Issue by wobblerr** [CF4x99/Apparition#1]
Well basically the title. Is it a ps3 version mod that is not supported to be compiled?

**Comment by CF4x99** [comment]
> Well basically the title. Is it a ps3 version mod that is not supported to be compiled?

What compiler are you using?

**Comment by wobbleris** [comment]
> > Well basically the title. Is it a ps3 version mod that is not supported to be compiled?
> 
> What compiler are you using?

I'm using the one you've put on your site, (https://github.com/LJW-Dev/Black-Ops-3-GSC-Compiler/releases/tag/1.0) and I get error no matter what I do. The precompiled one works though perfectly

**Comment by CF4x99** [comment]
> > > Well basically the title. Is it a ps3 version mod that is not supported to be compiled?
> > 
> > 
> > What compiler are you using?
> 
> I'm using the one you've put on your site, (https://github.com/LJW-Dev/Black-Ops-3-GSC-Compiler/releases/tag/1.0) and I get error no matter what I do. The precompiled one works though perfectly

Add me on discord: CF4_99#9999
It will be easier for me to help you.
