### ISSUE TITLE
Support for 720p resolution? (Steam Deck)

### ISSUE THREAD

**Issue by nielsbbb** [CF4x99/Apparition#4]
Hi

The mod menu falls out of the screen bounds.
I've tried to change the resolution or the advanced video options it keeps half on screen half out screen.
I added screenshots. Let's hope there is a fix
![PXL_20230823_184300346](https://github.com/CF4x99/Apparition/assets/105968798/252f5e55-6d2e-4ec1-9685-df8c283db8f0)
![PXL_20230823_184210736 MP](https://github.com/CF4x99/Apparition/assets/105968798/2c394980-766b-45ba-8687-e881e667985f)
![PXL_20230823_184248195](https://github.com/CF4x99/Apparition/assets/105968798/54f4db7f-ffda-4264-a462-42940d8d2e86)
![PXL_20230823_184220299](https://github.com/CF4x99/Apparition/assets/105968798/96c00828-ecb0-497a-8f88-4553a5cde44c)

**Comment by CF4x99** [comment]
Thank you for reporting the issue. I will have it fixed in the next update.
